name: 'Workflow Status Slack Notification'
description: 'Notify uppon workflow failure/success'
inputs:
  success:
    description: 'Workflow success'
    required: true
    default: 'false'
  slack-webhook:
    description: 'Webhook URL with token for notifications'
    required: true
    default: ''
  github-token:
    description: 'Status of the current run'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
  post-if: 'success()'
